version: 2.1

jobs:
  build:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: fix SwiftPM #Solves an old Xcode 11 issue that seems to got reintroduced with Xcode 12: https://stackoverflow.com/questions/58125659/github-actions-xcodebuild-fails-due-to-server-fingerprint
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run:
          name: Install bundler
          command: sudo gem install rake bundler:2.2.2
      - run:
          name: Install dependencies
          command: cd src/xcode && bundle install --path=vendor --jobs=8
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
  test:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: fix SwiftPM #Solves an old Xcode 11 issue that seems to got reintroduced with Xcode 12: https://stackoverflow.com/questions/58125659/github-actions-xcodebuild-fails-due-to-server-fingerprint
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run:
          name: Log Ruby Version
          command: ruby -v
      - run:
          name: Install bundler
          command: sudo gem install rake bundler:2.2.2
      - run:
          name: Install dependencies
          command: brew update-reset && brew install swiftlint && cd src/xcode && bundle install --path=vendor --jobs=8
      - run:
          name: Tests
          command: cd src/xcode && bundle exec fastlane test
      - restore_cache:
          key: sonar-cloud-v2
      - run:
          name: Convert coverage information to SonarCloud format
          command: |
            ./scripts/xcov_to_sonar.sh src/xcode/fastlane/test_output/action_0.xccovarchive/ $CIRCLE_WORKING_DIRECTORY/ src/xcode/fastlane/test_output/coverage.xml
      - run:
          name: Fix SwiftLint output for SonarCloud
          command: |
            ./scripts/fix_swiftlint_output.sh src/xcode/swiftlint.result.json
      - store_test_results:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/swiftlint.result.json
      - run:
          name: Skip SonarCloud for external Pull Requests
          command: '[[ -z "$CIRCLE_PR_REPONAME" ]] && circleci-agent step halt || true'
      - run:
          name: Install and run sonar-scanner
          command: |
            SCANNER=sonar-scanner-cli-4.3.0.2102-macosx
            SCANNERDIR=~/sonar/sonar-scanner-4.3.0.2102-macosx
            if [[ ! -x "$SCANNERDIR/bin/sonar-scanner" ]]; then
              curl -Ol https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SCANNER.zip
              unzip -qq -o $SCANNER.zip -d ~/sonar/
            fi
            chmod +x $SCANNERDIR/bin/sonar-scanner
            chmod +x $SCANNERDIR/jre/bin/java
            $SCANNERDIR/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN
          environment:
            SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io"}'
      - save_cache:
          key: sonar-cloud-v2
          paths:
            - ~/sonar/

  testflight-release:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: fix SwiftPM #Solves an old Xcode 11 issue that seems to got reintroduced with Xcode 12: https://stackoverflow.com/questions/58125659/github-actions-xcodebuild-fails-due-to-server-fingerprint
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run:
          name: Log Ruby Version
          command: ruby -v
      - run:
          name: Install dependencies
          command: cd src/xcode && bundle install --path=vendor --jobs=8 --frozen
      - run:
          name: fastlane
          command: cd src/xcode && bundle exec fastlane betaRelease
          
  production-release:
    macos:
      xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: fix SwiftPM #Solves an old Xcode 11 issue that seems to got reintroduced with Xcode 12: https://stackoverflow.com/questions/58125659/github-actions-xcodebuild-fails-due-to-server-fingerprint
          command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run:
          name: Log Ruby Version
          command: ruby -v
      - run:
          name: Install dependencies
          command: cd src/xcode && bundle install --path=vendor --jobs=8 --frozen
      - run:
          name: fastlane
          command: cd src/xcode && bundle exec fastlane productionRelease

workflows:
    process:
      jobs:
        - test
        - testflight-release:
            requires:
             - test
            filters:
              branches:
                only:
                  - staging
        - production-release:
            requires:
             - test
            filters:
              branches:
                only:
                  - release
